# Shell variables
# Generated by 'wal'
wallpaper='/home/tempora/wallpapers/animewall3.jpg'

# Special
background='#fefefe'
foreground='#7A5143'
cursor='#7A5143'

# Colors
color0='#fefefe'
color1='#F5B4AD'
color2='#DAC4BB'
color3='#BABCC4'
color4='#C4BFC7'
color5='#CFCCCD'
color6='#F9DAD2'
color7='#7A5143'
color8='#979695'
color9='#F5B4AD'
color10='#DAC4BB'
color11='#BABCC4'
color12='#C4BFC7'
color13='#CFCCCD'
color14='#F9DAD2'
color15='#7A5143'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
