#!/bin/sh

bspc rule -r "*"

sxhkd &
picom --experimental-backends &

nitrogen --restore 
./.config/polybar/polybar.sh &
pkill dunst &
dunst &
setxkbmap fi &
pulseaudio --start

. "${HOME}/.cache/wal/colors.sh"

bspc monitor DP-2 -d I II
bspc monitor HDMI-0 -d III



bspc config border_width                3
bspc config window_gap                  10
bspc config top_padding                 30
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config single_monocle              false
bspc config click_to_focus              true
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

bspc config normal_border_color               "$color1"
bspc config active_border_color               "$color2"
bspc config focused_border_color              "$color15"
bspc config presel_feedback_color             "$color1"
bspc config urgent_border_color               "#dd2727"

